### PR TITLE
Update ArtisanViewServiceProvider.php

### PR DESCRIPTION
**Pull request by sasin91**
shared & bindShared should be replaceable by call to app->singleton.
But since it's only commands getting registered, 
then making it a deferred ServiceProvider shouldn't be an issue. :)

### CODE REVIEW

**Comment by svenluijten** [comment]
Thanks! I'll check it out later. Did you test installing it locally?

**Comment by tomschlick** [comment]
Can confirm that this fixes the issue with 5.4. Just tested it locally.

**Comment by jkudish** [comment]
Can we see this merged? would be awesome 👍

**Comment by svenluijten** [comment]
Haven't been able to test it myself yet, super busy. I'll trust you guys and tag a new release 😃

**Comment by svenluijten** [comment]
I've tagged [1.3.2](https://github.com/svenluijten/artisan-view/releases/tag/1.3.2), that should fix the issue.

**Pull request merged**
