### PR TITLE
Add list:view command

### LINKED ISSUE #12: Add a list:view command
This command creates a tree-view of all files in the `/resources/views` directory.

### PR DESCRIPTION
**Pull request by patrikpihlstrom**
fixes #12

### CODE REVIEW

**Comment by patrikpihlstrom** [comment]
Not quite sure how to write tests for this one. Any ideas?

**Comment by svenluijten** [comment]
What I did for tests is I put all the logic in a seperate class and tested that. You could give that a shot instead of putting all the logic inside the command class itself 😄 

Also, could you rebase on master? This PR seems to include the changes from #14, somehow.

**Comment by svenluijten** [comment]
This PR is still showing the changes from the previous one you opened. Can you do the following and try again?

``` bash
git remote add upstream git@github.com:svenluijten/artisan-view.git
git pull --rebase upstream master
```

**Comment by patrikpihlstrom** [comment]
I don't really know what I'm doing in case you hadn't noticed 😨

**Pull request closed without merging**
